### ISSUE TITLE
KDE ISO 21.1 RC 2 gets stuck on boot (VMWare VM)

### ISSUE THREAD

**Issue by cfinnberg** [manjaro/release-review#12] opened 2021-07-24 07:55 UTC
The latest KDE ISO 21.1 RC2 (manjaro-kde-21.1-210723-linux513.iso) has a bug where it gets stuck during boot in a MHWD script in a VMWare Virtual Machine (it works fine in a Virtualbox VM)
![kuva](https://user-images.githubusercontent.com/2817326/126861698-eefabc60-e5af-4e30-90d5-b7b232b54f40.png)
I know VMWare is an unsupported platform, but just in case it has an easy solution, because RC1 (manjaro-kde-21.1-stable-staging-minimal-210720-linux513.iso) works fine in the same virtual machine.

**Comment by hphilm** [comment] 2021-07-24 09:00
We had an issue with **VirtualBox** config, which hopefully is solved by now. However, we have to see about **VMWare** once, more, which uses the same [config](https://gitlab.manjaro.org/applications/mhwd-db/-/blob/master/pci/graphic_drivers/video-virtualmachine/MHWDCONFIG).

**Comment by hphilm** [comment] 2021-07-24 09:59
![image](https://user-images.githubusercontent.com/5050022/126864965-4121a588-0896-474a-958a-c6054485e4ff.png)

There is a workaround to skip **mhwd** by adding `xdriver=vesa` to the kernel cmd line via `e` + `ctrl+x` after editing. For some reason the **mhwd-script** has an issue with installing the driver. So we have to see what blocks it. Tested with **vmware-workstation 16.1.2-3** from AUR.

**Comment by cfinnberg** [comment] 2021-07-24 10:14
With the `xdriver=vesa` option, it passes the mhwd script step, but it gets stuck at "_Reached target Graphical Interface_". I'm testing in VMWare Workstation 16.1.2 on Windows.

**Comment by hphilm** [comment] 2021-07-24 10:24
Well it works on the Manjaro host just fine. Also the script **mhwd-live** calls **mhwd** correctly. So this issue is odd. Will test with an updated version of that config ...

**Comment by cfinnberg** [comment] 2021-07-24 12:01
I tried also in my Manjaro host and I get same result than in Windows. Odd.

![kuva](https://user-images.githubusercontent.com/2817326/126867614-9420a557-b68c-4a39-99fc-a4f6ce07cc82.png)

I have been using UEFI in my VMs. Tried with BIOS and the only difference is that I get a black screen when it reaches graphical target (Both Linux and Windows hosts)

**Comment by hphilm** [comment] 2021-07-24 12:16
I've tested it now with the latest build shipping updated configs for **VMWARE**. Seems to work now: https://github.com/manjaro-gnome/download/releases/tag/202107241106. Download one of the **unstable** ISOs. I tested **gnome** minimal.

**Comment by cfinnberg** [comment] 2021-07-24 13:04
Tried `manjaro-gnome-21.07-development-unstable-210724-linux510.iso` file. Seems to work both in Linux and Windows. One thing I have noticed though is that open-vm-tools is not installed in the liveUSB and doesn't get installed after the installation. In RC1 or RC2, that was not an issue. Maybe that's expected because this ISO has older configs, but just you know.

**Comment by hphilm** [comment] 2021-07-24 13:30
I'm currently testing this [build](https://github.com/manjaro-gnome/download/releases/tag/202107241220). I missed a package so the config was skipped and no driver installed.

**Comment by cfinnberg** [comment] 2021-07-24 13:39
This build has the same problem that the RC2. It gets stuck in mhwd script. If I add the `xdriver=vesa` parameter, then it boots, but still no `open-vm-tools` in the live system.

**Comment by hphilm** [comment] 2021-07-24 14:49
Well if I use `xdriver=vesa` and modify the script `/usr/bin/mhwd-live` to not check for the `xdriver` value it runs thru and the driver got installed. However it simply hangs when you do it on the bootup. Will try now one of the Garuda ISOs, which is using **mwhd** also.

**Comment by hphilm** [comment] 2021-07-24 15:22
![image](https://user-images.githubusercontent.com/5050022/126873056-0dbca475-0767-4bbd-bfcd-ea358c891495.png)
same hanging ...

**Comment by hphilm** [comment] 2021-07-24 17:54
I might be on something: https://github.com/vmware/photon/blob/master/SPECS/open-vm-tools/vmtoolsd.service#L15 Since multi-user.target is not reached, enabling vmtoolsd might create the block when also trying to start it.

**Comment by cfinnberg** [comment] 2021-07-24 19:30
But in this case WantedBy means that when isolating multi-user.target it should start vmtoolsd, but not the other way around, isn't it? If we start vmtoolsd in other target, it should still work AFAIK.

I tested your latest [build](https://github.com/manjaro-gnome/download/releases/tag/202107241824) (unstable) and it's clear that vmtoolsd service is the key (system boots fine, vmtoolsd is enabled but not started). But is it really because of the WantedBy or is it something else?

**Comment by hphilm** [comment] 2021-07-24 19:40
Well, latest build works. So it confirms my Theory. Since the **mhwd-live.service** runs with graphical.target it can't start services with multi-user.wants targets. Let's see how [Garuda](https://gitlab.com/garuda-linux/applications/mhwd-db-garuda/-/issues/1) will solve it.

**Comment by hphilm** [comment] 2021-07-24 20:01
seems we start it on our end before a [user session](https://gitlab.manjaro.org/tools/development-tools/manjaro-tools-livecd/-/blob/master/data/sd/mhwd-live.service#L3) gets enabled. So in the end it is tricky, as the timing of the two services is off and therefore the lockdown caused by **wanted-by**

**Comment by hphilm** [comment] 2021-07-24 20:32
let's see if **mhwd-db-0.6.5-13** fixes it by passing --no-block ...

**Comment by cfinnberg** [comment] 2021-07-24 21:05
I think it should work. My theory is that the `After=display-manager.service` in [vmtoolsd.service](https://github.com/archlinux/svntogit-community/blob/master/open-vm-tools/repos/community-x86_64/vmtoolsd.service#L4) is the one that is blocking the whole thing. As display-manager is also scheduled to start (due to the graphical target) vmtoolsd wants to wait for it because of the `After=`. But as we are starting vmtoolsd in synchronous way, display-manager (or any other unit) can't start before vmtoolsd is started.
I'm confident that `--no-block` is going to solve the thing, as now even if vmtoolsd waits for display-manager, the boot process don't need to wait for it and can continue starting other units. When display-manager starts, then vmtoolsd will be started too.

**Comment by boredland** [comment] 2024-05-07 00:02
closing for being ages old.

**Closed as completed by boredland** 2024-05-07 00:02 UTC
